apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: redbee-env
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: redbee-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi