apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "deploy python api redbee challenge"
  name: redbee-challenge
  namespace: redbee-env
  labels:
    app: simponsquotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simponsquotes
  template:
    metadata:
      labels:
        app: simponsquotes
    spec:
      containers:
      - name: simponsquotes-api
        image: fidelgonzalez/simpsons-quotes:0.1.3
        #liveness probe
        livenessProbe:
          httpGet:
            path: /quotes
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
        #end liveness probe
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: db-host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: db-port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password                
        ports:
        - containerPort: 8000
